site_name: ""
site_url: https://1nit.online
theme:
  name: material
  language: fr
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.footer
  palette:
    scheme: default
    primary: white
    accent: grey
    font:
      text: Roboto
      code: Inconsolata
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/arctenis
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nicolas-chartier-b48092239
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Accueil: index.md
  - Django: django/apprendre_django.md
  - Elixir: 
    - Apprendre Elixir: elixir/apprendre_elixir.md
    - Lancer Elixir: elixir/01_lancer_elixir.md
    - Pattern Matching: elixir/02_pattern_matching.md
  - Python:
    - Variables: python/variables.md
    - Slicing: python/slicing.md
    - Unpacking: python/unpacking.md
    - Projets:
      - Pomodoro: python/projet_pomodoro.md
